# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
    ]
