# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 12:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='phone_num',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. 10 digits allowed.", regex='^(\\+?1?\\d{10})|(\\+?1?\\d{13})$')]),
        ),
        migrations.AlterField(
            model_name='smsdetail',
            name='to',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. 10 digits allowed.", regex='^(\\+?1?\\d{10})|(\\+?1?\\d{13})$')]),
        ),
    ]
