# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsdetails', '0002_auto_20170608_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsdetail',
            name='sent_by',
        ),
        migrations.AlterField(
            model_name='smsdetail',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsdetails.ContactDetail'),
        ),
    ]
