# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsdetails', '0003_auto_20170608_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdetail',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='smsdetail',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
