# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsdetails', '0004_auto_20170608_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsdetail',
            options={'ordering': ['-id']},
        ),
    ]
