# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsdetails', '0005_auto_20170609_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdetail',
            name='message_body',
            field=models.CharField(help_text='Maa Charecter length: 160', max_length=160),
        ),
    ]
