# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsdetails', '0006_auto_20170609_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdetail',
            name='message_body',
            field=models.CharField(help_text='Max Charecter length: 160', max_length=160),
        ),
        migrations.AlterField(
            model_name='smsdetail',
            name='to',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
