# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsdetails', '0007_auto_20170613_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdetail',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsdetails.ContactDetail'),
        ),
    ]
