# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 16:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsdetails', '0010_auto_20170613_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdetail',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smsdetails.ContactDetail'),
        ),
        migrations.AlterField(
            model_name='smsdetail',
            name='to',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
