# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsdetails', '0013_auto_20170613_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdetail',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smsdetails.ContactDetail'),
        ),
    ]
