# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsdetails', '0014_auto_20170613_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsdetail',
            name='contact',
        ),
        migrations.AddField(
            model_name='smsdetail',
            name='contact',
            field=models.ManyToManyField(blank=True, null=True, to='smsdetails.ContactDetail'),
        ),
    ]
