# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsdetails', '0015_auto_20170614_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsdetail',
            name='contact',
        ),
        migrations.AddField(
            model_name='smsdetail',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smsdetails.ContactDetail'),
        ),
    ]
