# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 07:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsdetails', '0018_smsdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='phone_num',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. 10 digits allowed.", regex='^\\+?1?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='smsdetail',
            name='to',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. 10 digits allowed.", regex='^\\+?1?\\d{10}$')]),
        ),
    ]
